version: 2.1

# Reusable Snippets!
#
# These are re-used by the various tests below, to avoid repetition.
#
commands:
  install_desired_npm:
    description: "Install the same consistent version of npm"
    steps:
      - run:
          # Due to a bug, npm upgrades from the version of npm that ships with
          # Node.js 6 (npm v3.10.10) go poorly and generally causes other problems
          # with the environment.  Since yarn is already available here we can just
          # use that to work-around the issue.  It's possible that npm cleanup might
          # prevent this from being necessary, but this installation can be switched
          # to use `npm` (rather than `yarn`) once Node 6 is no longer tested below.
          name: Install npm@6, but with yarn.
          command: sudo yarn global add npm@6

  # These are the steps used for each version of Node which we're testing
  # against.  Thanks to YAMLs inability to merge arrays (though it is able
  # to merge objects), every version of Node must use the exact same steps,
  # or these steps would need to be repeated in a version of Node that needs
  # something different.  Probably best to avoid that, out of principle, though.
  common_test_steps:
    description: "Commands to run on every Node.js environment"
    steps:
      - install_desired_npm
      - checkout
      - restore_cache:
          keys:
            # When lock file changes, use increasingly general patterns to restore cache
            - npm-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-v2-{{ .Branch }}-
            - npm-v2-
      - run: npm --version
      - run: npm ci
      - save_cache:
          key: npm-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            # This should cache the npm cache instead of node_modules, which is needed because
            # npm ci actually removes node_modules before installing to guarantee a clean slate.
            - ~/.npm
      - run:
          command: npm run test:ci
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - run: npm run coverage:upload
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit

  install_and_start_verdaccio:
    description: "Run and start the Verdaccio server"
    steps:
      - run:
          name: Verdaccio
          command: npx verdaccio
          background: true

executors:
  node:
    parameters:
      tag:
        type: string
        default: '10'
    docker:
      - image: circleci/node:<< parameters.tag >>
    environment:
      DEBUG: lerna

# Important! When adding a new job to `jobs`, make sure to define when it
# executes by also adding it to the `workflows` section below!
jobs:
  # Platform tests, each with the same tests but different platform or version.
  # The docker tag represents the Node.js version and the full list is available
  # at https://hub.docker.com/r/circleci/node/.

  # NODE: Note certain tests are currently being skipped for Node.js 6.
  NodeJS 6:
    executor: { name: node, tag: '6' }
    steps:
      - common_test_steps

  NodeJS 8:
    executor: { name: node, tag: '8' }
    steps:
      - common_test_steps

  NodeJS 10:
    executor: { name: node, tag: '10' }
    steps:
      - common_test_steps
      # We will save the results of this one particular invocation to use in
      # the publish step. Not only does this make the publishing step take less
      # time, this also ensures that a passing version gets deployed even if,
      # theoretically, rebuilding the same commit on the same version of
      # Node.js should yield the same results!
      - persist_to_workspace:
          root: .
          paths:
            - ./**

  NodeJS 12:
    executor: { name: node, tag: '12' }
    steps:
      - common_test_steps

  Dry-run publish:
    executor: { name: node, tag: '10' }
    steps:
      # Bring in the workspace which we saved in the 'NodeJS 10' job above.
      # This has the benefit of only publishing the exact build that we tested,
      # in addition to not having to re-build it another time.
      - attach_workspace:
          at: .
      - run:
          name: Write Verdaccio config for dummy server W/O proxy
          command: |
            mkdir -p ~/.config/verdaccio/
            cat \<<'EOF' > ~/.config/verdaccio/config.yaml
            # Store the files on disk.  We'll use this directory as a build
            # artifact and gain access to all of the packages which are
            # published to this server.
            storage: ./storage
            # By not specifying any uplinks, we will avoid proxying through
            # to npm.  This allows publishing of this build's packages
            # irregardless of whether they are already published to npm.
            uplinks: # None
            # Normally, publishing isn't possible without an uplink.
            publish:
              allow_offline: false
            # Allow any package to be published to this (local) server with
            # no authentication.
            packages:
              '**':
                access: $all
                publish: $all
            logs:
              - {type: stdout, format: pretty, level: http}
            EOF
      - install_and_start_verdaccio
      - run:
          name: Publish to (local) Verdaccio
          command: |
            npx lerna publish \
              --no-git-tag-version \
              --no-push \
              --registry=http://localhost:4873/ \
              --yes \
              from-package
      - store_artifacts:
          path: ~/.config/verdaccio/storage/
          destination: packed

  Publish:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Write Verdaccio config for dummy server w/ proxy
          command: |
            mkdir -p ~/.config/verdaccio/
            cat \<<'EOF' > ~/.config/verdaccio/config.yaml
            storage: ./storage
            uplinks:
              npmjs:
                url: https://registry.npmjs.org/
            publish:
              allow_offline: false
            packages:
              '**':
                access: $all
                publish: $all
                proxy: npmjs
            logs:
              - {type: stdout, format: pretty, level: http}
            EOF
      - install_and_start_verdaccio
      - run:
          name: Publish
          command: |
            # This should be set automatically on tag-triggered builds.
            if [ -z "$CIRCLE_TAG" ]; then
              echo 'ERROR! $CIRCLE_TAG is not set.'
              exit 1
            fi

            # Get the actual hash the tag points to.
            TAG_REF="$(git rev-list -n1 "$CIRCLE_TAG")"

            # Fail if we couldn't get it.
            if [ -z "$TAG_REF" ]; then
              echo "ERROR! Couldn't get \$TAG_REF."
              exit 1
            fi

            # Ensure the annotated tag points to a 'Release' commit.
            RELEASE_COMMIT_MSG="$(git log --format=%s -n 1 $TAG_REF)"
            if ! echo "$RELEASE_COMMIT_MSG" | grep -qE '^Release$'; then
              echo "ERROR! The 'publish/' tags must be on 'Release' commits."
              exit 1
            fi

            # See if there are Lerna packages tagged (e.g. matching pkg@x.y.z)
            # by checking what _tags_ point to the hash.  The expectation is
            # that there _must_ be Lerna packages tagged in the same ref that
            # the `publish/` tag points to.
            TAGS="$(git tag --points-at $TAG_REF)"
            NON_PUBLISH_TAGS="$(echo "$TAGS" | grep -vE '^publish/[0-9]+')"
            VERSION_TAGS="$(echo "$NON_PUBLISH_TAGS" | grep -E '^.+@.+$')"
            if [ -z "$VERSION_TAGS" ]; then
              echo "ERROR! There must be at least some other packages tagged."
              exit 1
            fi

            # Ensure the annotated publish tag is formatted expectedly.
            # This could certainly be more defensive, but currently just ensures
            # that the annotated message starts with 'Publish'.
            PUBLISH_TAG_MSG="$(git tag -l --format='%(contents)' $CIRCLE_TAG)"
            if ! echo "$PUBLISH_TAG_MSG" | grep -qE '^Publish'; then
              echo "ERROR! The 'publish/' tags must be annotated correctly."
              echo "       Be certain to use the npm-scripts when publishing."
              exit 1
            fi

            # If there's a dist-tag, we'll publish to that instead of 'latest'.
            DIST_TAG="$(echo "$PUBLISH_TAG_MSG" |
              sed -E 's/^Publish($|( \(dist-tag:([a-z-]+)\))$)/\3/')"

            # Default to latest if we couldn't extract anything from the
            # annotated `publish/` tag.
            if [ -z "$DIST_TAG" ]; then
              DIST_TAG="latest"
            fi

            echo "Publishing to npm under the $DIST_TAG tag."

            npx lerna publish --registry=http://localhost:4873 \
              --dist-tag="$DIST_TAG" from-git --yes

            if [ -z "$SLACK_WEBHOOK_URL" ]; then
              exit 1
            fi

            # Add bullet-points and links to the markdown links.
            MARKDOWN_VERSIONS="$(echo "$VERSION_TAGS" |
              sed -E 's%^(.+)@(.+)$%• <https://npm.im/\1|\`\1@\2\`>\\n%')"

            cat \<<EOM | curl -X POST -H 'Content-type: application/json' --data @- $SLACK_WEBHOOK_URL
            {
              "text": "New packages have been published to the \`$DIST_TAG\` tag:\n\n$MARKDOWN_VERSIONS",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":npm:  *The following packages have been published to the \`$DIST_TAG\` tag*\n\n> ⚠️🚧 This is not real *yet*.\n\n*Packages:*\n\n$MARKDOWN_VERSIONS"
                  }
                }
              ]
            }
            EOM
      - run:
          name: Post to Slack on Failure
          command: |
            if [ -z "$SLACK_WEBHOOK_URL" ]; then
              echo 'Cannot post failure to Slack because $SLACK_WEBHOOK_URL is not set.'
              exit 1
            fi

            cat \<<EOM | curl -X POST -H 'Content-type: application/json' --data @- $SLACK_WEBHOOK_URL
            {
              "text": "A failure occurred during publishing.  For more information, see $CIRCLE_BUILD_URL.",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":boom: *Failure during publishing!* :broken_heart:\n\n<$CIRCLE_BUILD_URL|See the build details for more information!>"
                  }
                }
              ]
            }
            EOM
          when: on_fail
      - store_artifacts:
          path: ~/.config/verdaccio/storage/
          destination: published

# XXX We used to use this filter to only run a "Docs" job on docs branches.
#     Now we use it to disable all jobs. It's unclear if there's a simpler way
#     to do this!
common_job_filters: &common_job_filters
  filters:
    branches:
      # If 'docs' is found, with word boundaries on either side, skip.
      ignore: /.*?\bdocs\b.*/
    # Ensure every job has `tags` filters since the publish steps have tags.
    # This is some wild configuration thing that's pretty hard to figure out.
    tags:
      only: /.*/

workflows:
  version: 2
  Build:
    jobs:
      - NodeJS 6:
          <<: *common_job_filters
      - NodeJS 8:
          <<: *common_job_filters
      - NodeJS 10:
          <<: *common_job_filters
      - NodeJS 12:
          <<: *common_job_filters
      - Dry-run publish:
          <<: *common_job_filters
          requires:
            - NodeJS 6
            - NodeJS 8
            - NodeJS 10
            - NodeJS 12
      - Publish:
          requires:
            - Dry-run publish
          filters:
            tags:
              only: /^publish\/[0-9]+$/
            # We want the publish to trigger on the above tags, not any branch.
            branches:
              ignore: /.*/
