title: Apollo Server
propertytitle: Using Apollo Server
subtitle: Apollo Server
description: A guide to using Apollo Server.
version: 1
versions:
  - '2'
  - '1'
sidebar_categories:
  null:
    - index
    - example
    - setup
    - requests
    - graphiql
  Servers:
    - servers/express
    - servers/hapi
    - servers/koa
    - servers/lambda
    - servers/micro
    - servers/restify
    - servers/azure-functions
    - servers/adonis
  Related:
    - '[Monitoring and caching](https://www.apollographql.com/docs/engine/setup-node.html)'
    - '[graphql-tools](https://www.apollographql.com/docs/graphql-tools/)'
    - '[GraphQL Subscriptions](https://www.apollographql.com/docs/graphql-subscriptions/)'
    - '[Production deployment](https://dev-blog.apollodata.com/graphql-over-rest-with-node-heroku-and-apollo-engine-fb8581f8d77f)'
  Migration:
    - migration-one-dot
    - migration-hapi
    - migration

github_repo: apollographql/apollo-server
content_root: docs/source

typescript_api_box:
  data_file: docs.json

url: https://www.apollographql.com/docs/apollo-server/
root: /docs/apollo-server/

public_dir: public/docs/apollo-server

versioned-netlify-redirects:
  netlify_site_id: apollo-server-docs
